// Generated by gencpp from file custom_messages/RobotStatus.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_ROBOTSTATUS_H
#define CUSTOM_MESSAGES_MESSAGE_ROBOTSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_messages
{
template <class ContainerAllocator>
struct RobotStatus_
{
  typedef RobotStatus_<ContainerAllocator> Type;

  RobotStatus_()
    : header()
    , robot_id(0)
    , is_ready(false)  {
    }
  RobotStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_id(0)
    , is_ready(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _robot_id_type;
  _robot_id_type robot_id;

   typedef uint8_t _is_ready_type;
  _is_ready_type is_ready;





  typedef boost::shared_ptr< ::custom_messages::RobotStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_messages::RobotStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatus_

typedef ::custom_messages::RobotStatus_<std::allocator<void> > RobotStatus;

typedef boost::shared_ptr< ::custom_messages::RobotStatus > RobotStatusPtr;
typedef boost::shared_ptr< ::custom_messages::RobotStatus const> RobotStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_messages::RobotStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_messages::RobotStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_messages::RobotStatus_<ContainerAllocator1> & lhs, const ::custom_messages::RobotStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_id == rhs.robot_id &&
    lhs.is_ready == rhs.is_ready;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_messages::RobotStatus_<ContainerAllocator1> & lhs, const ::custom_messages::RobotStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_messages::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_messages::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd4a4a969111c2fb5d233f5f91bb2733";
  }

  static const char* value(const ::custom_messages::RobotStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd4a4a969111c2fbULL;
  static const uint64_t static_value2 = 0x5d233f5f91bb2733ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_messages::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_messages/RobotStatus";
  }

  static const char* value(const ::custom_messages::RobotStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_messages::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 robot_id\n"
"bool is_ready\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_messages::RobotStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_messages::RobotStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_id);
      stream.next(m.is_ready);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_messages::RobotStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_messages::RobotStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_id);
    s << indent << "is_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_ready);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_ROBOTSTATUS_H
