// Generated by gencpp from file custom_services/MeanThreeInts.msg
// DO NOT EDIT!


#ifndef CUSTOM_SERVICES_MESSAGE_MEANTHREEINTS_H
#define CUSTOM_SERVICES_MESSAGE_MEANTHREEINTS_H

#include <ros/service_traits.h>


#include <custom_services/MeanThreeIntsRequest.h>
#include <custom_services/MeanThreeIntsResponse.h>


namespace custom_services
{

struct MeanThreeInts
{

typedef MeanThreeIntsRequest Request;
typedef MeanThreeIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MeanThreeInts
} // namespace custom_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_services::MeanThreeInts > {
  static const char* value()
  {
    return "f30a58e2837f4b803e4927983e2be21f";
  }

  static const char* value(const ::custom_services::MeanThreeInts&) { return value(); }
};

template<>
struct DataType< ::custom_services::MeanThreeInts > {
  static const char* value()
  {
    return "custom_services/MeanThreeInts";
  }

  static const char* value(const ::custom_services::MeanThreeInts&) { return value(); }
};


// service_traits::MD5Sum< ::custom_services::MeanThreeIntsRequest> should match
// service_traits::MD5Sum< ::custom_services::MeanThreeInts >
template<>
struct MD5Sum< ::custom_services::MeanThreeIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_services::MeanThreeInts >::value();
  }
  static const char* value(const ::custom_services::MeanThreeIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_services::MeanThreeIntsRequest> should match
// service_traits::DataType< ::custom_services::MeanThreeInts >
template<>
struct DataType< ::custom_services::MeanThreeIntsRequest>
{
  static const char* value()
  {
    return DataType< ::custom_services::MeanThreeInts >::value();
  }
  static const char* value(const ::custom_services::MeanThreeIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_services::MeanThreeIntsResponse> should match
// service_traits::MD5Sum< ::custom_services::MeanThreeInts >
template<>
struct MD5Sum< ::custom_services::MeanThreeIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_services::MeanThreeInts >::value();
  }
  static const char* value(const ::custom_services::MeanThreeIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_services::MeanThreeIntsResponse> should match
// service_traits::DataType< ::custom_services::MeanThreeInts >
template<>
struct DataType< ::custom_services::MeanThreeIntsResponse>
{
  static const char* value()
  {
    return DataType< ::custom_services::MeanThreeInts >::value();
  }
  static const char* value(const ::custom_services::MeanThreeIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_SERVICES_MESSAGE_MEANTHREEINTS_H
