// Generated by gencpp from file clear_map_service/GetMapRequest.msg
// DO NOT EDIT!


#ifndef CLEAR_MAP_SERVICE_MESSAGE_GETMAPREQUEST_H
#define CLEAR_MAP_SERVICE_MESSAGE_GETMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clear_map_service
{
template <class ContainerAllocator>
struct GetMapRequest_
{
  typedef GetMapRequest_<ContainerAllocator> Type;

  GetMapRequest_()
    {
    }
  GetMapRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::clear_map_service::GetMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clear_map_service::GetMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetMapRequest_

typedef ::clear_map_service::GetMapRequest_<std::allocator<void> > GetMapRequest;

typedef boost::shared_ptr< ::clear_map_service::GetMapRequest > GetMapRequestPtr;
typedef boost::shared_ptr< ::clear_map_service::GetMapRequest const> GetMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clear_map_service::GetMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clear_map_service::GetMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace clear_map_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clear_map_service::GetMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clear_map_service::GetMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clear_map_service::GetMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clear_map_service::GetMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clear_map_service::GetMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clear_map_service::GetMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clear_map_service::GetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::clear_map_service::GetMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::clear_map_service::GetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clear_map_service/GetMapRequest";
  }

  static const char* value(const ::clear_map_service::GetMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clear_map_service::GetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Get the map as a nav_msgs/OccupancyGrid\n"
;
  }

  static const char* value(const ::clear_map_service::GetMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clear_map_service::GetMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clear_map_service::GetMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::clear_map_service::GetMapRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CLEAR_MAP_SERVICE_MESSAGE_GETMAPREQUEST_H
