// Generated by gencpp from file clear_map_service/GetMap.msg
// DO NOT EDIT!


#ifndef CLEAR_MAP_SERVICE_MESSAGE_GETMAP_H
#define CLEAR_MAP_SERVICE_MESSAGE_GETMAP_H

#include <ros/service_traits.h>


#include <clear_map_service/GetMapRequest.h>
#include <clear_map_service/GetMapResponse.h>


namespace clear_map_service
{

struct GetMap
{

typedef GetMapRequest Request;
typedef GetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMap
} // namespace clear_map_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clear_map_service::GetMap > {
  static const char* value()
  {
    return "6cdd0a18e0aff5b0a3ca2326a89b54ff";
  }

  static const char* value(const ::clear_map_service::GetMap&) { return value(); }
};

template<>
struct DataType< ::clear_map_service::GetMap > {
  static const char* value()
  {
    return "clear_map_service/GetMap";
  }

  static const char* value(const ::clear_map_service::GetMap&) { return value(); }
};


// service_traits::MD5Sum< ::clear_map_service::GetMapRequest> should match
// service_traits::MD5Sum< ::clear_map_service::GetMap >
template<>
struct MD5Sum< ::clear_map_service::GetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clear_map_service::GetMap >::value();
  }
  static const char* value(const ::clear_map_service::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clear_map_service::GetMapRequest> should match
// service_traits::DataType< ::clear_map_service::GetMap >
template<>
struct DataType< ::clear_map_service::GetMapRequest>
{
  static const char* value()
  {
    return DataType< ::clear_map_service::GetMap >::value();
  }
  static const char* value(const ::clear_map_service::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clear_map_service::GetMapResponse> should match
// service_traits::MD5Sum< ::clear_map_service::GetMap >
template<>
struct MD5Sum< ::clear_map_service::GetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clear_map_service::GetMap >::value();
  }
  static const char* value(const ::clear_map_service::GetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clear_map_service::GetMapResponse> should match
// service_traits::DataType< ::clear_map_service::GetMap >
template<>
struct DataType< ::clear_map_service::GetMapResponse>
{
  static const char* value()
  {
    return DataType< ::clear_map_service::GetMap >::value();
  }
  static const char* value(const ::clear_map_service::GetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLEAR_MAP_SERVICE_MESSAGE_GETMAP_H
